# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='s_id',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='s_id',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
