# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20170128_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='complainant',
            name='user',
            field=models.OneToOneField(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='root.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='user',
            field=models.OneToOneField(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='root.User'),
            preserve_default=False,
        ),
    ]
