# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20170128_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
