# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_auto_20170128_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainant',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'twitter')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'resolved'), (2, 'rejected')]),
        ),
    ]
